config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/search', to: 'users#search'
  
  resources :sessions, only: [:create, :destroy]
  resources :invites, only: [:create]

  namespace :api do
    namespace :v1 do
      resources :trips
      resources :users
    end
  end

  resources :trips do
    member do
      get :join
    end
  end
  resources :users
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  validates               :name, 
                          :description, 
                          :date, 
                          :resort_id, presence: true
  
  has_and_belongs_to_many :users
  
  belongs_to              :resort
  
  has_many                :instas

  belongs_to :owner, class_name: 'User'

  mount_uploader :coverphoto, CoverphotoUploader

  def has_user?(user)
    users.include?(user)
  end

  def add_user(user)
    users << user
  end

  def photos
    photos = self.users.map do |user|
              if user.instagram_id
                GetUserInstas.new.perform(user, self) 
              end
            end
    photos.flatten
  end

  def get_tweets(date)
    tweets = users.map do |user|
      user.get_tweets(date)
    end
    tweets.flatten.sort_by { |t| t.created_at }.reverse
  end


  def self.sort_by_date
    all.sort_by { |trip| trip.date }
  end
end

app/controllers/api/v1/trips_controller.rb
class Api::V1::TripsController < ApplicationController
  respond_to :json, :xml, :html

  def index
    respond_with Trip.all
  end

  def show
    respond_with Trip.find(params[:id])
  end

  def create
    Trip.create!(safe_params)
    head :ok
  end

  def update
    trip = Trip.find(params[:id])
    trip.update(safe_params)
    head :ok
  end

  def destroy
    trip = Trip.find(params[:id])
    trip.destroy
    head :ok
  end

private

  def safe_params
    params.require(:trip).permit(:name, 
                                 :description,  
                                 :date, 
                                 :trip_location,
                                 :resort_id)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
include ForecastHelper

  def index
    @trips = Trip.sort_by_date.reverse
  end

  def show
    @trip   = Trip.find(params[:id])
    @invite = Invite.new
    @resort = Resort.find(@trip.resort_id)
    @instas = @trip.instas
    trip_forecast(@trip)
  end

  def new
    @trip    = Trip.new
    @resorts = Resort.all
  end

  def create
    @trip = Trip.create(trip_params.merge owner_id: current_user.id)
    @trip.users << current_user
    if @trip.save
      flash[:success] = "Your trip has been created, the stoke is high!"
      redirect_to trip_path(@trip)
    else
      flash[:warning] = "Bummer, your trip ain't gonna happen, so gnar!"
      redirect_to new_trips_path
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    @trip.update(trip_params)
    flash[:success] = "Werd yo, your trip is totally up to date!"
    redirect_to trip_path(@trip)
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    flash[:danger] = "Your trip has totally been abolished!"
    redirect_to '/'
  end

  def join
    @trip = Trip.find(params[:id])
    @trip.add_user(current_user)
    redirect_to :back
  end

private

  def trip_params
    params.require(:trip).permit(:name,
                                 :description,
                                 :date,
                                 :resort_id,
                                 :coverphoto,
                                 :owner_id)
  end
end

app/helpers/trips_helper.rb
module TripsHelper
  def user_can_join(trip)
    current_user && trip.users.none? { |u| u == current_user }
  end  
end

app/views/trips/_email_form.html.erb
<div class="thumbnail" id="email">
    <%= form_for @invite, :html => {:class => "form-horizontal col-md-12"} do |f| %>
      <div class="form-group">
        <%= f.text_area   :to , :class => 'form-control', :placeholder => "friends@example.com" %>
      </div>
      <%= f.hidden_field :trip, value: @trip.id %>
      <div class="form-group">
        <%= f.text_field  :subject , :class => 'form-control', :placeholder => "Subject" %>
      </div>

      <div class="form-group">
        <%= f.text_area   :body , :class => 'form-control', :placeholder => "Message" %>
      </div>
      <div class="form-group">
        <%= f.submit  "Send Email" , :class => 'btn btn-info btn-block' %>
      </div>
    <% end %>
</div>

app/views/trips/_feed.html.erb
<h3 class="site-text">Check out what our members are up to!</h3>

<div class="row">
  <%= 4.times do %>
    <% trip = @trips.sample %>
    <div class="col-md-3">
      <div class="thumbnail">
        <div class="caption">
          <p class="site-txt-b"><%= link_to "#{trip.name}", trip_path(trip) %></p>
          <p class="site-txt-b"><%= truncate(trip.description, length: 70) %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/trips/_forecast.html.erb
<h2 class="site-text">Current Forecast for:<br/> <%= @resort.name %></h2>
    
      <p class="forecast">
        Summary: <%= @forecast [:hourly][:summary] %><br/>
        Precipitation: <%= @forecast [:currently][:precipType] %><br/>
        Temperature: <%= @forecast [:currently][:temperature] %><br/>
        Windspeed: <%= @forecast [:currently][:windSpeed] %>
      </p>

app/views/trips/_form.html.erb
  <%= form_for @trip, :html => {multipart: true, class: "form-horizontal"} do |f| %>
    <div>
      <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
          <%= f.text_field :name, :class => 'form-control', :placeholder => "Trip Name: e.g. Susan's Birthday Bash" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
          <%= f.text_area :description, :class => 'form-control', :placeholder => "Description: e.g. Sick trip with the bros" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
          <p class="site-txt-b">
            <%= f.label :cover_photo, class: "control-label" %>
            <%= f.file_field :coverphoto, :class => 'form-control'%>
          </p>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-8 col-md-offset-2">
          <p class="site-txt-b">
            <%= f.label "Resort:", class: "control-label"%>
            <%= f.collection_select :resort_id, Resort.order(:name),:id, :name, include_blank: false, class: "form-control" %>
           &nbsp
            <%= f.label "Trip Date:", class: "control-label"%>
            <%= date_select :trip, :date, class: "form-control"%>
          </p>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
          <%= f.submit "Submit", :class => 'btn btn-lg btn-primary btn-block' %>
        </div>
      </div>
    </div>
  <% end %>

app/views/trips/_photo_feed.html.erb
<div class="panel" id="feed">
  <div class="panel-heading">
    <h1>Insta Feed</h1>
  </div>
</div>
  <% @trip.photos.each_with_index do |photo, id| %>
  <% if photo %>
    <div class="col-md-4" id="photo">
      <img src=<%= photo.thumbnail_url %> data-toggle="modal" data-target="#photoModal<%= id %>"></img>
    </div>

<div class="modal fade" id="photoModal<%= id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" id="photo">
    <div class="modal-content">
      <div class="modal-body">
        <img src=<%= photo.full_size_url%>></img>
      </div>
    </div>
  </div>
</div>
<% end %>
<% end %>

app/views/trips/_twitter_feed.html.erb
<div class="panel" id="feed">
  <div class="panel-heading">
    <h1>Twitter Feed</h1>
  </div>
</div>
<div class="scroll-feed">
<% @trip.get_tweets(@trip.date).each do |t| %>
<div class="thumbnail" id="feed">
      <div class="caption">
        <p class="text pull-right"><%= t.created_at.strftime('%l:%M %p') %></p>
        <p><img class="img-circle" src=<%="#{t.user.profile_image_url}"%> style="width: 25px; height: 25px;"></p>
        <h4 class="text"><%= "@#{t.user.screen_name}" %></h4>
        <a href=<%= t.url %>><%= t.text %></a>
    </div>
  </div>
<% end %>
</div>

app/views/trips/edit.html.erb
<div class="jumbotron">
  <h2 class="site-text">Edit your trip!</h2>
  <%= render partial: "form" %>
</div>

app/views/trips/index.html.erb
<div class="jumbotron">
<h2 class="site-text">Our Members Trips</h2>
</div>

<div class="row">
  <% @trips.each do |trip| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= image_tag trip.coverphoto, style: "height: 150px; width: 150px; margin-top: 10px;" %>
        <div class="caption">
          <h3 class="site-text"> <%= link_to trip.name, trip_path(trip) %> </h3>
          <p class="site-text"> 
            They are going to <%= trip.resort.name %> on <%= trip.date.strftime("%m/%d/%Y") %><br/>
            <%= trip.description %> 
          </p> 
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/trips/new.html.erb
<div class="jumbotron">
  <% if current_user %>
    <h2 class="site-text">Plan your trip!</h2>
    <%= render partial: "form" %>
  <% else %>
    <h3 class="site-text">Please sign in</h3>
    <p class="site-txt-b">You will need to sign in if you would like to plan a trip<br/>
    <%= link_to "Sign In with Twitter", "/auth/twitter", class: "center-btn btn btn-lg btn-primary" %></p> 
  <% end %>
</div>

app/views/trips/show.html.erb
<div class="row">
  <div class="col-md-9" id="trip">
    <div class="panel" id="trip">
      <div class="panel-heading">
        <%= image_tag @trip.coverphoto, class: "trip-img pull-right" %>
        <h1 style="text-align: center;"><%= @trip.name %></h1>
        <% if current_user.id == @trip.owner_id %>
        <div style="text-align: center;">
          <%= link_to "Edit Trip", edit_trip_path(@trip), class: "btn btn-sm btn-warning" %>
          <%= link_to "Delete Trip", trip_path(@trip), method: :delete, class: "btn btn-sm btn-danger" %>
        </div>
        <% end %>
        <p><h4 class="trip-date">We are going to <%= @resort.name %> on <%= @trip.date.strftime("%m / %d / %Y")%></h4></p><br/>
        <p class="trip-des"><%= @trip.description %></p>
          <%= render partial: "forecast" %>
      </div>
    </div>
    <div class="col-md-4" id="feed-title">
      <%= render partial: 'twitter_feed' %>
    </div>
    <div class="col-md-8" id="feed-title">
      <%= render partial: 'photo_feed' %>
    </div>
  </div>
    <div class="col-md-3">
      <div class="sidebar-offcanvas">
        <div class="list-group">
          <% if @trip.has_user?(current_user) %>
            <li class="list-group-item" id="trip"><h2 style="text-align: center;">Invite friends</h2></li>
            <%= render partial: 'email_form' %>
        <% end %>
          <li class="list-group-item" id="users">
            <h2>
              Who's going 
              <% if user_can_join(@trip) %>
                <%= link_to "Join this trip!", join_trip_path(@trip), class: "btn btn-primary pull-right" %>
              <% end %>
            </h2>
          </li>
          <div class="scroll-feed">
            <% @trip.users.each do |user| %>
              <li class="list-group-item" id="trip"><h4><%= link_to user.name, user_path(user) %></h4></li>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>