config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/search', to: 'users#search'
  
  resources :sessions, only: [:create, :destroy]
  resources :invites, only: [:create]

  namespace :api do
    namespace :v1 do
      resources :trips
      resources :users
    end
  end

  resources :trips do
    member do
      get :join
    end
  end
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :trips
  has_many :instas

  has_many :trips, foreign_key: :owner_id
  
  mount_uploader :avatar, AvatarUploader

  after_create :get_insta_id

  def has_epic_mix_data?
    epic_mix_username != nil
    epic_mix_password != nil
  end

  def epic_mix_client
    @epic_mix_client = Epicmix::Client.new(epic_mix_username, 
                                           epic_mix_password)
  end

  def get_tweets(date)
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = Figaro.env.twitter_id 
      config.consumer_secret     = Figaro.env.twitter_secret 
      config.access_token        = Figaro.env.twitter_access_token 
      config.access_token_secret = Figaro.env.twitter_access_token_secret
    end

    tweets = client.user_timeline(twitter_username)
    tweets.select { |t| t.created_at.strftime('%m/%d/%Y') == date.strftime('%m/%d/%Y') }
  end

  def get_insta_id
    if self.instagram_username
      id = InstaGetId.new.perform(self.instagram_username)
      self.instagram_id = id
      self.save
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider          = auth["provider"]
      user.uid               = auth["uid"]
      user.name              = auth["info"]["name"]
      user.email             = auth["info"]["email"]
      user.twitter_username  = auth["info"]["nickname"]
      user.image            = auth["info"]["image"]
    end
  end

  def self.find_matches(query)
    query = query.downcase
    where("lower(name) like ?", "%#{query}%")
  end
end

app/controllers/api/v1/users_controller.rb
require 'epicmix'

class Api::V1::UsersController < ApplicationController
  respond_to :json

  def index
    respond_with User.all
  end

  def show
    respond_with User.find(params[:id])
  end

  def create
    User.create!(safe_params)
    head :ok
  end

  def update
    user = User.find(params[:id])
    user.update(safe_params)
    head :ok
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    head :ok
  end

private

  def safe_params
    params.require(:user).permit(:name,
                                 :email,
                                 :instagram_username,
                                 :instagram_id, 
                                 :twitter_username, 
                                 :epic_mix_username, 
                                 :epic_mix_password,
                                 :provider,
                                 :uid,
                                 :image
                                )
  end
end

app/controllers/users_controller.rb
require 'epicmix'

class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user   = User.find(params[:id])
    @trips  = @user.trips.reverse
    @client = Epicmix::Client.new(@user.epic_mix_username, 
                                  @user.epic_mix_password)
  end

  def new
    @user = User.new  
  end

  def create
    @user          = User.create!(user_params)
    flash[:notice] = "Your profile is totally legit!"
    redirect_to user_path(@user)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = "Your profile has been fully updated, lookin freshy!"
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Your profile has been abolished"
    redirect_to '/'
  end

  def search
    @users = User.find_matches(params[:query])
  end

private

  def user_has_trips?(user)
    if user.trips != nil
      @user_trips = user.trips
    end
  end

  def user_params
    params.require(:user).permit(:name, 
                                 :email,
                                 :avatar,
                                 :epic_mix_username, 
                                 :epic_mix_password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_epic_mix_data.html.erb
<h3 class="mix-title">Your Epicmix stats for: </h3>
<p class="mix-title">The <%= @client.season_stats.last['year'] %> season</p>
<p class="mix-data">
  Vertical Feet: <%= @client.season_stats.last['verticalFeet'] %><br/>
  Runs: <%= @client.season_stats.last['numberOfLifts'] %><br/>
  Day on the Mountain: <%= @client.season_stats.last['daysOnMountain'] %>
</p>

app/views/users/_user_form.html.erb
<%= form_for @user, :html => {multipart: true, class: "form-horizontal"} do |f| %>
    <div>
      <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
          <%= f.text_field :name, :class => 'form-control', :placeholder => "Your Name" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
          <%= f.text_field :email, :class => 'form-control', :placeholder => "Email" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
          <p class="site-txt-b">
            <%= f.label :Profile_Photo, class: "control-label" %>
            <%= f.file_field :avatar, :class => 'form-control'%>
          </p>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
          <%= f.text_field :epic_mix_username, :class => 'form-control', :placeholder => "Epic Mix Username" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
          <%= f.text_field :epic_mix_password, :class => 'form-control', :placeholder => "Epic Mix Password" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
          <%= f.submit :submit, :class => 'btn btn-lg btn-primary btn-block' %>
        </div>
      </div>
    </div>
  <% end %>

app/views/users/edit.html.erb
<div class="jumbotron">
  <h2 class="site-title">Edit your profile</h2>
  <%= render partial: "user_form" %>
</div>

app/views/users/index.html.erb
<div class="jumbotron">
  <div class="table">
    <% @users.each do |user| %>
      <%= link_to user.name, user_path(user) %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="jumbotron">
  <h2 class="site-title">Sign up now!</h2>
  <%= render partial: "user_form" %>
</div>

app/views/users/search.html.erb
 <div class="col-md-8">
  <div class='jumbotron'>
    <% @users.each do |user| %>
      <h1><%= link_to user.name, user_path(user) %></h1>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="panel" id="users">
      <div class="panel-heading text">
        <img class="img-circle" src=<%="#{@user.avatar}"%> style="width: 140px; height: 140px;">
        <h1 class="pull-right"><%= @user.name %></h1>
      </div>
    </div>
    <div class="jumbotron">
      <div class="person-btn">
        <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-sm btn-warning" %>
        <%= link_to "Delete Profile", user_path(@user), method: :delete, class: "btn btn-sm btn-danger" %>
      </div>
      <h3 class="text">Add your Instagram account</h3>
        <div class="col-md-6" id="instagram">
          <%= form_for @user do |f| %>
            <div class="input-group">
              <%= f.text_field :instagram_username, :class => "form-control", :placeholder => "snowcial" %>
              <span class="input-group-btn">
                <%= f.submit "Submit", :class => "btn btn-info" %>
              </span>
            </div>
            <% end %>
          </div>
        </div>
    <div class="col-lg-6">
      <div class="mix-data">
        <% if @user.has_epic_mix_data? %>
          <%= render partial: "epic_mix_data", client: @user.epic_mix_client %>
        <% else %>
          <p>Add your epic mix info to your profile to see it here!</p>
        <% end %>
      </div>
    </div>
  <div class="col-md-4">
    <div class="user-scroll-feed">
    <% @trips.each do |trip| %>
      <div class="thumbnail" id="trip">
        <div class="caption">
          <h2 class="text pull-right"><%= trip.date.strftime('%b') %></h2> 
          <h2 class="text pull-right"><%= trip.date.strftime('%d') %></h2>
          <h3><%= link_to trip.name, trip_path(trip) %></h3>
          <h4 class="text"><%= trip.resort.name %></h4>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>