config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/search', to: 'users#search'
  
  resources :sessions, only: [:create, :destroy]
  resources :invites, only: [:create]

  namespace :api do
    namespace :v1 do
      resources :trips
      resources :users
    end
  end

  resources :trips do
    member do
      get :join
    end
  end
  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snowcial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <span class="glyphicon glyphicon-tree-conifer"></span>Snowcial
      </a>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Trips", trips_path %></li>
        <li>
          <form action='/search' class='search'>
            <input type='text' name='query' value='search users' class='search-text-box'> 
          </form>
        </li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Plan a Trip", new_trip_path%></li>
        <% if current_user %>
          <li><%= link_to "Welcome #{current_user.name}!", user_path(current_user) %></li>
          <li><%= link_to "Sign Out", signout_path %></li> 
        <% else %>
          <li><%= link_to "Sign In with Twitter", "/auth/twitter" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
  <div class="alert-background text-center">
    <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>">
        <%= message %>
      </div>
    <% end %>
  </div>

<%= yield %>

</body>
</html>
<script>
  $('.search-text-box').focus(function() {
    $(this).val('');
  })
  $('.search-text-box').blur(function() {
    $(this).val('search users');
  })
</script>